In [1]:
import xarray as xr

In [2]:
ds = xr.open_dataset('bcg_tau_obs_3.nc')

for var in ds.variables:
    newvar = 'belli_' + var.split('_')[1] 
    ds = ds.rename({var: newvar})

ds.to_netcdf('bcg_tau_obs_3b.nc')

<xarray.Dataset> Size: 582B
Dimensions:        (iOBS: 3)
Dimensions without coordinates: iOBS
Data variables: (12/13)
    ihop_descr     (iOBS) |S30 90B ...
    ihop_date      (iOBS) <U19 228B ...
    ihop_YYYYMMDD  (iOBS) float64 24B ...
    ihop_HHMMSS    (iOBS) float64 24B ...
    ihop_np        (iOBS) float64 24B ...
    ihop_x         (iOBS) float64 24B ...
    ...             ...
    ihop_z         (iOBS) float64 24B ...
    ihop_tau       (iOBS) float64 24B ...
    ihop_ang       (iOBS) float64 24B ...
    ihop_uncert    (iOBS) float64 24B ...
    ihop_iter      (iOBS) int64 24B ...
    ihop_val       (iOBS) float64 24B ...

In [10]:
ds = xr.open_dataset('bcg-grid.nc')
ds

<xarray.Dataset> Size: 704B
Dimensions:           (nrange: 6, nidw: 4)
Coordinates:
  * nrange            (nrange) int64 48B 0 1 2 3 4 5
  * nidw              (nidw) int64 32B 0 1 2 3
Data variables:
    ihop_ranges       (nrange) float64 48B ...
    ihop_xc           (nrange, nidw) float64 192B ...
    ihop_yc           (nrange, nidw) float64 192B ...
    ihop_idw_weights  (nrange, nidw) float64 192B ...

In [16]:
for var in ds.variables:
    if var.split('_')[0]!='ihop':
        continue
    if var.split('_')[1]=='ranges' or var.split('_')[1]=='xc' or var.split('_')[1]=='yc':
        newvar = 'belli_' + var.split('_')[1]
        ds = ds.rename({var: newvar})
    elif var.split('_')[1]=='idw':
        newvar = 'belli_' + var.split('_')[1] + '_' + var.split('_')[2]
        ds = ds.rename({var: newvar})

ds.to_netcdf('bcg_gridb.nc')

In [20]:
ds = xr.open_dataset('bcg_tau_obs_3.nc')

In [26]:
ds.belli_YYYYMMDD.data

array([20210101., 20210101., 20210101.])

In [23]:
ds.belli_iter.data

array([6, 7, 8])

In [28]:
import numpy as np
ds.belli_date.values = np.array(['2021-01-01T20:00:00', '2021-01-01T22:00:00',
       '2021-01-01T24:00:00'], dtype='<U19')
ds.to_netcdf('bcg_tau_obs_3b.nc')

In [27]:
ds.belli_HHMMSS.data

array([20000., 22000., 24000.])